### ISSUE TITLE
`useFetcher()` support

### ISSUE THREAD

**Issue by w00ing** [Code-Forge-Net/remix-hook-form#17]
Hey, I'm trying to use remix-hook-form with a `<fetcher.Form>` returned from `useFetcher()` hook. I supplied `onSubmit` props of the `<fetcher.Form>` with `handleSubmit()` function returned from `useRemixForm()`. However, it seems that the `fetcher.state` does not change when I submit the form. And `useRemixForm()` does not seem to have any related options. Do you have plans on supporting it?

**Comment by AlemTuzlak** [comment]
@w00ing You are correct, I think this is doable, I will be adding a custom fetcher export from the package that provides a form that works well with the package. For now what you can do is provide a custom onSubmit to the hook that is going to use the fetcher to submit instead of the default behavior (which uses useSubmit hook under the hood) but you would still need to roll with your own error handling in this case!

**Comment by AlemTuzlak** [comment]
Added in 1.2, you can pass in your fetcher

**Comment by w00ing** [comment]
> Added in 1.2, you can pass in your fetcher

Cool! Thank you :)
