### ISSUE TITLE
`formState.isSubmitSuccessful` does not behave like react-hook-form

### ISSUE THREAD

**Issue by geemanjs** [Code-Forge-Net/remix-hook-form#32]
Hey 

I noticed that `formState.isSubmitSuccessful` always remains `false`

Likely #22 but very different..  

### Actual behaviour
`isSubmitSuccessful` is always `false` even after a successful submission

### Expected behaviour
Upon submitting the form and it completing successfully `isSubmitSuccessful` remains `true` until a subsequent `reset` is called (like react-hook-form) (https://www.react-hook-form.com/api/useformstate/ and https://www.react-hook-form.com/api/useform/reset/)

### Possible solution
I'm unsure how this would work given the action response is handled by the developer rather than this library. But thought i'd post the issue and see if you had any ideas!

**Comment by AlemTuzlak** [comment]
@geemanjs hmm well the real puzzle here for me is is this needed because if the submit is successful the action will probably redirect you or something? But I guess if it was submitted via fetcher it would stay on same page, can you tell me your use-case so I can think about what would be the best approach in Remix world?

**Comment by lucgagan** [comment]
I think similar issue to https://github.com/Code-Forge-Net/remix-hook-form/issues/39
