### ISSUE TITLE
How to handle submit success?

### ISSUE THREAD

**Issue by lucgagan** [Code-Forge-Net/remix-hook-form#39]
```ts
  const {
    data,
    errors,
    receivedValues: defaultValues,
  } = await getValidatedFormData<FormData>(request, resolver);

  if (errors) {
    return json({ defaultValues, errors });
  }

  // router.push(`/article/${data.id}/outline`);

  return json(data);
};

export default () => {
  const form = useRemixForm<FormData>({
    mode: 'onSubmit',
    resolver,
  });

  // toast({
  //   title: 'Article Project Created',
  // });
```

My use case is that I want to trigger toast after successful action.

**Comment by AlemTuzlak** [comment]
@lucgagan if you want to redirect to somewhere with a toast notification you can use:
https://github.com/Code-Forge-Net/remix-toast
If you want to return the data to frontend and show a notification on the same screen you can just use
```jsx
const data = useActionData();
useEffect(() => {
  if(data){
    toast(...)
  }
},[data])
```
but yeah this issue is not related to the library itself it's just a matter of how you implement it so I will close it, but the above approaches will work

**Comment by lucgagan** [comment]
Thank you
